Eliminate .sh extension from shell scripts (#635)
## Ticket

Resolves #620 

## Changes

- Remove `.sh` extension from scripts
- Remove `.sh` from everywhere called and mentioned

## Context for reviewers

[google shell style
guide](https://google.github.io/styleguide/shellguide.html)

Regarding the Lint Markdown CI check failing, it is finding two dead
links since I changed the file names. These should be resolved on
merging.

```
  ERROR: 1 dead links found!
  [✖] https://github.com/navapbc/template-infra/tree/main/template-only-bin/download-and-install-template → Status: 404

  ERROR: 1 dead links found!
  [✖] https://github.com/navapbc/template-infra/blob/main/template-only-bin/update-template#L17-L28 → Status: 404
```

## Testing
[platform-test
branch](https://github.com/navapbc/platform-test/tree/daphnegold/620-remove-shell-extensions)
[successful deploy to
platform-test](https://github.com/navapbc/platform-test/actions/runs/9552254403)
[platform-test PR](https://github.com/navapbc/platform-test/pull/106)

---------

Co-authored-by: Loren Yu <loren@navapbc.com>